#!/bin/bash
if [[ -z "$OPENAI_API_KEY" ]]
then
  echo "genie: OPENAI_API_KEY is unset"
  exit 1
fi

if [ $# -eq 0 ]
then
    echo "genie: no arguments supplied"
    echo "usage: genie [command]"
    exit 1
fi

if [ -t 0 ]
then
    echo "genie: no input provided on stdin"
    echo "example usage: ls -la | genie [command]"
    exit 1
fi

function assign() {
  raw=$(
    echo "Determine whether the listed task should be assigned to Human Secretary or Computer Algorithm."
    echo ""
    echo "Task: Summarize this report."
    echo "Assign to: Human Secretary"
    echo ""
    echo "Task: Compute total profit and loss."
    echo "Assign to: Computer Algorithm"
    echo ""
    echo "Task: $1"
    echo "Assign to:"
  )
  prompt=$(echo "$raw" | jq -sR .)
  curl https://api.openai.com/v1/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d "{\"model\": \"text-davinci-003\", \"prompt\": $prompt, \"temperature\": 0, \"max_tokens\": 1000}" \
    -# | jq -r .choices[0].text
}

function get_completion() {
  curl https://api.openai.com/v1/completions \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d "{\"model\": \"text-davinci-003\", \"prompt\": $1, \"temperature\": 0, \"max_tokens\": 1000}" \
    -# | jq -r .choices[0].text
}

triage=$(assign "$1")
if [ "$triage" = "Computer Algorithm" ]
then
  prompt=$(echo -e "Generate a bash script that performs the following transformation on the contents of stdin\n\nTransformation: $1\nResult:" | jq -sR .)
  get_completion "$prompt" > scratch.sh
  chmod +x scratch.sh
  ./scratch.sh
else
  input_txt=$(cat)
  prompt=$(echo -e "Perform a transformation on this input text:\n\n$input_txt\n\nTransformation: $1\nResult:" | jq -sR .)
  get_completion "$prompt"
fi

